<a href="https://colab.research.google.com/github/mahmud-nobe/CS110_Assignments/blob/master/CS110%20Assignment%203%3A%20Bloom%20Filters/CS110_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [0]:
NAME = ""
COLLABORATORS = ""

---


# CS110 Spring 2020 Assignment - Indexing Techniques and Data Structures.


## Overview

 In this assignment, you  will research  Counting Bloom Filters (CBFs), which are data structures that extend the standard Bloom Filters. You will design and implement in Python a set of CBFs initialized at a given false positive rate, and will need to summarize your findings in a report. A report structured has been provided for you in the form of enumerated tasks, which you should follow.
 
 ## Intended Style and Key Audience
 
Your report needs to be written in the style of a chapter from the Cormen textbook (i.e., exhibiting academic rigor and clear explanations) or a Wikipedia page on the subject (i.e., a general overview on a topic that will be peer-reviewed by the world-wide community). Thus, with a beginner’s audience in mind, your report needs to: 

* Carefully explain the concepts of a CBFs, 
* Include details on your CBFs design, 
* Perform an analysis of your implementation and experimental results pertaining to your Python implementation and 
* Perform a critical comparison analysis between the experimental results and the theoretically predicted ones. 
* Use the provided code cells to include all your code, and if these are not enough, please add more cells which you deem necessary.
* Use the same function names provided in the template. 
* Thoroughly describe the algorithmic strategies you are employing in a given question. To do so, feel free to include extra Markdown cells whenever relevant--you may find this [how-to-guide](https://medium.com/analytics-vidhya/the-ultimate-markdown-guide-for-jupyter-notebook-d5e5abf728fd) helpful. 

Make sure you properly cite your sources of information. 

## Notes on the Submission Materials

1. Your **first resource** should be a PDF file created from the Jupyter notebook template provided in these instructions. If your name is “Dumbledore”, your PDF should be named “Dumbledore.pdf”.
2. Your **second resource** must be a single Jupyter Notebook named “Dumbledore.ipynb”. Alternatively, you can also submit a zip file that includes your Jupyter notebook, but please make sure to name it “Dumbledore.zip” (if your name is Dumbledore, the Jupyter notebook submitted as part of such zip file should still be named “Dumbledore.ipynb”!).

## Notes on the Grading Rubrics

* This is a strictly individual assignment. Everything you submit must reflect your own writing and coding. Please do refer to the course guidelines on the syllabus namely in what constitutes plagiarism. 
* All the tasks will be graded on the indicated companion LOs; please make sure to consult their descriptions and rubrics in the course syllabus to maximally align your approach to them. You will not be penalized for not attempting the optional challenge.
* As per the course’s policy on the syllabus, you will need to footnote **at least three HCs** by including a meaningful justification of the application of each HC and how they enabled you to complete part of your work on this assignment. Please refer to [these guidelines](https://docs.google.com/document/d/1s7yOVOtMIaHQdKLeRmZbq1gRqwJKfezBsfru9Q6PcHw/edit) on how to incorporate HCs in your work.

## Report Structured Tasks

### Task 1. [#responsibility] [appropriate LO for the make-up work] 

Take a screenshot of your CS110 dashboard on Forum where the following is visible: 
* your name. 
* your absences for the course have been set to excused up to the end of week 7 (inclusively). Submit this screenshot as a PNG file on your Jupyter notebook. 

In [0]:
# YOUR CODE HERE
raise NotImplementedError()

### Task 2.  [#ComputationalSolutions, #DataStructures, #ComplexityAnalysis]  

Write a summary  of the CBFs as an indexing technique, with their underlying data structure and  hashing functionality. This is,  list all the operations they support. For all CBF operations, include an analysis of their asymptotic order growth (complexity analysis). Give a few examples of practical, real-life computational applications that can benefit from using CBFs and carefully justify why. 

YOUR ANSWER HERE

### Task 3. [#DataStructures, #PythonProgramming, #CodeReadability] 

Implement in Python 3 your designed CBFs data structure and all its operations using the code template below. Make sure you carefully organize your Python code, write meaningful comments (feel free to use [docstrings](https://www.python.org/dev/peps/pep-0257/)), and provide a thorough justification for your choice of hash functions. 

If you decide to use the Python library  `mmh3`,  you will need to provide a thorough explanation of why you have chosen the hashing functions therein. You may also use  `numpy`, `matplotlib`, `random`, `statistics`, and `math`. If you plan to use any other external library not mentioned in this list, you will need to contact your instructor first for validation.

Make sure to strictly follow the honor code as any plagiarism attempt will be referred to the ASC. Please refer to [resource1](https://new.library.arizona.edu/research/citing/plagiarism) and [resource2](https://poorvucenter.yale.edu/writing/using-sources/understanding-and-avoiding-plagiarism/what-plagiarism), which specify what constitutes plagiarism. 

Demonstrate how your code works by inserting a list of words in [Shakespeare’s works](https://ocw.mit.edu/ans7870/6/6.006/s08/lecturenotes/files/t8.shakespeare.txt). The following lines of code will create such a list of words in Python:

```python
txt_file = open("t8.shakespeare.txt", "r")

entries = txt_file.read().split(' ')
lines = [string.replace('\n', '') for string in entries]
all_text = [line for line in lines if line != '']
```

Feel free to use another interesting dataset for further validation, but this is optional.

In [0]:
# Feel free to define additional classes that you think are helpful 
# in building this class of CountingBloomFilter 

import numpy as np
# import mmh3

class CountingBloomFilter(object):
    """Implement the counting bloom filter which supports:
    - search: queries the membership of an element
    - insert: inserts a string to the filter
    - delete: removes a string from the filter 
    
    Feel free to define any helpful additional methods.
    """
    def __init__(self, num_item, fpr):
        """
        /YOUR ARGUMENTS/ are the two parameters of your choice from the 
        following parameters of a CBF:
        - fpr: float, false positive rate
        - memory_size: int, memory size
        - num_item: int, number of items stored
        - num_hashfn: int, number of hash functions
        
        For example, if you choose fpr and memory_size, edit your __init__ to
        `def __init__(self, memory_size, fpr)`
        """
        # false positive rate
        self.fpr = fpr

        # memory size
        self.memory_size = -1*int( (num_item * math.log(fpr)) / (math.log(2)**2) )
        
        # initialize an empty numpy array as our hash table
        self.hash_table = np.zeros(self.memory_size, dtype= np.int8)

        # number of hash functions
        self.num_hashfn = 6 #TESTING
    
    def hash_cbf(self, item):
        """
        Returns hash values of an item
        [ADD ADDITIONAL DESCRIPTION, IF NEED BE]
        """
        hashed_slots = []

        for num in range(self.num_hashfn):
          slot = mmh3.hash(item, seed = 5*num) % self.memory_size
          hashed_slots.append(slot)

        return hashed_slots
    
    def search(self, item):
        """
        [YOUR FUNCTION DESCRIPTION]
        """
        hashed_slots = self.hash_cbf(item)

        for slot in hashed_slots:
          if (self.hash_table[slot] == 0):
            return False
        
        return True
    
    def insert(self, item):
        """
        [YOUR FUNCTION DESCRIPTION]
        """
        hashed_slots = self.hash_cbf(item)

        for slot in hashed_slots:
          self.hash_table[slot] += 1
    
    def delete(self, item):
        """
        [YOUR FUNCTION DESCRIPTION]
        """
        if (search(self, item)):
          hashed_slots = self.hash_cbf(item)

          for slot in hashed_slots:
            self.hash_table[slot] -= 1
        else:
          KeyError('{} not found in counting_bloom_filter'.format(item))
        


In [0]:
txt_file = open("t8.shakespeare.txt", "r")
 
entries = txt_file.read().split(' ')
lines = [string.replace('\n', '') for string in entries]
all_text = [line for line in lines if line != '']

In [0]:
np.random.shuffle(all_text)
nwords_to_add = int(len(all_text) * 0.7)

present = all_text[:nwords_to_add]
absent = all_text[nwords_to_add:]

np.random.shuffle(present)
np.random.shuffle(absent)

In [57]:
num_item = 20
fpr = 0.05

CBFs = CountingBloomFilter(num_item, fpr)

for word in present[:1000]:
  CBFs.insert(word)

testing_words = present[:1000] + absent[:500]

true_positive = 0
false_positive = 0

for word in testing_words:
  is_found = CBFs.search(word)

  if (is_found and word not in present):
    print(word)
    false_positive += 1 
  else:
    true_positive += 1

total_positive = false_positive + true_positive
print('True Positive, False Positive, False Positive Rate:',true_positive, false_positive, false_positive/(total_positive))

glorify
Eighty
Taxation!
fatal.
ache
fleshly
DON
spurs!
playfellow.
orderly;
accoutrement,
cicatrices
bowsprit,
True Positive, False Positive, False Positive Rate: 1487 13 0.008666666666666666


In [31]:
#testing shell

import math

#!pip install mmh3
import mmh3
mmh3.hash('foo', 1)

item = 9
print()
print('{} not found in counting_bloom_filter'.format(item))
import numpy as np
slots = [1,2,3]
key = np.array([3,0,0,0,7,5])
np.append(key, 4)
print(key[slots] == 0)
print(key)
#else:
 # print(slots)


n = 10
p = 0.6
m =  -1*int( (n * math.log(p)) / (math.log(2)**2) )
print(m) 

np.random.sample()


9 not found in counting_bloom_filter
[ True  True  True]
[3 0 0 0 7 5]
10


'him'

In [75]:
num_item = 20
fpr = 0.05

CBFs = CountingBloomFilter(num_item, fpr)
print(CBFs.hash_table[:10])
print(CBFs.memory_size)
CBFs.memory_size = 10
print(CBFs.memory_size)

for word in present[:200]:
  CBFs.insert(word)

[0 0 0 0 0 0 0 0 0 0]
124
10


In [76]:
len(CBFs.hash_table)
print(CBFs.hash_table[:10])

[ 122  114  100  109 -123 -117  126  120  104 -123]


### Task 4 [#ComplexityAnalysis, #ComputationalCritique].

Now you will verify the effectiveness of your CBF implementation by testing how well the implementation matches or diverges from the theoretical findings. The following tasks will help you make this computational analysis. Explicitly include any assumptions you have made to arrive at your results. If there are any discrepancies between the theory and the computational experiments, provide an explanation for these.

1. [#DataStructures] Create several CBFs (at least 10) for different FPRs, and evaluate how the memory size scales with the FPR. 
2. [#DataStructures] How does the memory size scale with the number of items stored, for a fixed FPR?
3. [#DataStructures, #ComplexityAnalysis] How does the actual FPR scale with the number of hash functions?
4. [#DataStructures, #ComplexityAnalysis] How does the access time to hashed values scale with the number of items stored in a CBF kept at constant FPR?


YOUR ANSWER HERE

### Task 5. [#ComputationalCritique]

Identify and list (if any) corner cases for CBFs. Explain why these cases should be taken into account if you are a software engineer.


YOUR ANSWER HERE